# Generated by Django 5.2.8 on 2025-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_instructorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
    ]
