# Generated by Django 5.2.8 on 2025-12-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_instructorprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='website',
        ),
    ]
