# Generated by Django 5.2.8 on 2025-12-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_instructorprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='resume',
        ),
    ]
