# Generated by Django 5.2.8 on 2025-11-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_liveclass_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
