# Generated by Django 5.2.8 on 2025-12-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_module_order_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
