# Generated by Django 5.2.8 on 2025-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_liveclass_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='structure_json',
            field=models.JSONField(default=dict),
        ),
    ]
