# Generated by Django 5.2.8 on 2025-12-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_module_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Module', 'Module'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Live Class', 'Live Class')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
