# Generated by Django 5.2.8 on 2025-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_courseblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
